image: ubuntu:20.04

before_script:
    - apt-get update
    - apt-get -y --force-yes install xvfb
    - apt -y --force-yes install build-essential apt-transport-https lsb-release ca-certificates curl
    - curl -sL https://deb.nodesource.com/setup_12.x | bash -
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
    - apt-get -y --force-yes install google-chrome-stable
    - apt -y --force-yes install nodejs
    - node -v
    - npm install

stages:
    - test
    
tryTest:
    stage: test
    script:
        # - npm test
        - xvfb-run -a --server-args="-screen 0 1280x800x24 -ac -nolisten tcp -dpi 96 +extension RANDR" npm test 