image: node:12.16.1

before_script:
    - sudo apt-get install xvfb
    - npm install

stages:
    - test
    
tryTest:
    stage: test
    script:
        # - npm test
        - xvfb-run -a --server-args="-screen 0 1280x800x24 -ac -nolisten tcp -dpi 96 +extension RANDR" npm test 