image: ubuntu:20.04

before_script:
    - apt-get update
    - apt-get -y --force-yes install xvfb
    - npm install

stages:
    - test
    
tryTest:
    stage: test
    script:
        # - npm test
        - xvfb-run -a --server-args="-screen 0 1280x800x24 -ac -nolisten tcp -dpi 96 +extension RANDR" npm test 