image: ubuntu:20.04

before_script:
    - apt-get update
    - apt-get -y --force-yes install xvfb
    - apt -y --force-yes install build-essential apt-transport-https lsb-release ca-certificates curl
    - curl -sL https://deb.nodesource.com/setup_12.x | bash -
    - apt install nodejs
    - node -v
    - npm install

stages:
    - test
    
tryTest:
    stage: test
    script:
        # - npm test
        - xvfb-run -a --server-args="-screen 0 1280x800x24 -ac -nolisten tcp -dpi 96 +extension RANDR" npm test 