version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=${mode}
    ports:
      - 3000:3000
    command: npm start